apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: pdf-coordinates
  labels:
    name: backend
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 5005
      targetPort: 5005
      protocol: TCP
      name: debug
  selector:
    app: backend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pdf-coordinates
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: backend
          image: pearsonk27/pdf-coordinates-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 5005
              name: debug
          resources:
            requests:
              cpu: 125m
              memory: 500Mi
              ephemeral-storage: "1Gi"
            limits:
              cpu: 250m
              memory: 1000Mi
              ephemeral-storage: "2Gi"
          envFrom:
            - configMapRef:
                name: postgres-configmap
            - configMapRef:
                name: spring-boot-configmap
            - secretRef:
                name: postgres-credentials
